### ISSUE TITLE
link to one variable distributions is broken

### ISSUE THREAD

**Issue by cduvallet** [MIT-BECL/awesome-becl-resources#10]
On the main readme, the link to "Plotting One Variable Distributions - BECL-produced resource for plotting bar graphs, boxplots, violin plots, and more. Includes example data set and raw code files." is broken.

I'm guessing it should go to somewhere in [this repo](https://github.com/MIT-BECL/Plotting-Distributions)?

**Comment by mrsunny0** [comment]
I am not the one who fixed it, but I believe it is now correctly addressing https://github.com/MIT-BECL/Plotting-Distributions.
